// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Input: typeof import('./components/chat/input.vue')['default']
    Login: typeof import('./components/auth/login.vue')['default']
    Message: typeof import('./components/chat/message.vue')['default']
    Navbar: typeof import('./components/navbar.vue')['default']
    Register: typeof import('./components/auth/register.vue')['default']
  }
}

export { }
